### ISSUE TITLE
Plans for upgrade to typeorm 0.3?

### ISSUE THREAD

**Issue by omerd-cyera** [viniciusjssouza/typeorm-transactional-tests#6]
Are there any plans to update this lib to typeorm 0.3?

**Comment by viniciusjssouza** [comment]
Hi @od-cyera :wave: 

I have plans, but didn't have time for this yet :confused:

**Comment by omerd-cyera** [comment]
Cool. I'm pretty sure a rename of `Connection` to `DataSource`. will do the trick.
Worked for me, but I didn't test it thoroughly. Seems a little weird to open a PR on this small change, but i can do it. are you accepting PRs?

**Comment by omerd-cyera** [comment]
Opened a PR for the upgrade #7

**Comment by viniciusjssouza** [comment]
@od-cyera versions 2.x.x are compatible with typeorm 0.3.x now. Can you test it on your side?

Thanks for the PR

**Comment by omerd-cyera** [comment]
Yes, ill test it and inform you. thanks :)

**Comment by omerd-cyera** [comment]
Works fine on my end. Thanks again. :)
